/* Lógico_1: */

CREATE TABLE CLIENTE (
    ID_CLIENTE SERIAL PRIMARY KEY,
	NOME_CLIENTE VARCHAR (60),
    DT_NASC DATE NOT NULL, 
    SEXO CHAR (1),
    ENDERECO CHAR (60),
    TELEFONE CHAR (15),
    CPF VARCHAR(11),
	CNPJ CHAR (14)
);

CREATE TABLE FUNCIONARIO (
    NOME_FUNCIONARIO CHAR (60),
    SEXO_FUNCIONARIO CHAR(1),
    DT_nasc DATE NOT NULL,
    ENDERECO CHAR (60),
    TELEFONE CHAR (14),
    ID_FUNCIONARIO SERIAL PRIMARY KEY
);

CREATE TABLE PRODUTO (
    ID_PRODUTO SERIAL PRIMARY KEY,
    NOME_PRODUTO CHAR (60),
    QUANTIDADE INTEGER,
    COD__BARRAS_ CHAR(13)
);

CREATE TABLE VENDA_CLIENTE_FUNCIONARIO_PRODUTO (
    FK_CLIENTE_ID_CLIENTE INTEGER,
    FK_FUNCIONARIO_ID_FUNCIONARIO INTEGER,
    FK_PRODUTO_ID_PRODUTO INTEGER
);
 
ALTER TABLE VENDA_CLIENTE_FUNCIONARIO_PRODUTO ADD CONSTRAINT FK_VENDA_CLIENTE_FUNCIONARIO_PRODUTO_1
    FOREIGN KEY (FK_CLIENTE_ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE)
    ON DELETE NO ACTION;
 
ALTER TABLE VENDA_CLIENTE_FUNCIONARIO_PRODUTO ADD CONSTRAINT FK_VENDA_CLIENTE_FUNCIONARIO_PRODUTO_2
    FOREIGN KEY (FK_FUNCIONARIO_ID_FUNCIONARIO)
    REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
    ON DELETE NO ACTION;
 
ALTER TABLE VENDA_CLIENTE_FUNCIONARIO_PRODUTO ADD CONSTRAINT FK_VENDA_CLIENTE_FUNCIONARIO_PRODUTO_3
    FOREIGN KEY (FK_PRODUTO_ID_PRODUTO)
    REFERENCES PRODUTO (ID_PRODUTO)
    ON DELETE NO ACTION;